name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24'
          cache: true
      - name: Download Go modules
        run: go mod download -x
      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          VERSION_VAR="-X main.version=${{ github.ref_name }}"
          BINARY_NAME="fbcli"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="fbcli.exe"
          fi
          go build -v -ldflags="$VERSION_VAR" -o "${BINARY_NAME}"
          ASSET_NAME="fbcli-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip "${ASSET_NAME}.zip" "${BINARY_NAME}"
          else
            tar -czvf "${ASSET_NAME}.tar.gz" "${BINARY_NAME}"
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fbcli-${{ matrix.goos }}-${{ matrix.goarch }}
          path: fbcli-${{ matrix.goos }}-${{ matrix.goarch }}.*
          retention-days: 1

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## fbcli ${{ github.ref_name }}
            
            Cross-platform binaries for fbcli (File Browser CLI).
            
            ### Downloads:
            - **Linux amd64**: `fbcli-linux-amd64.tar.gz`
            - **Linux arm64**: `fbcli-linux-arm64.tar.gz` 
            - **Windows amd64**: `fbcli-windows-amd64.zip`
            
            ### Installation:
            ```bash
            # Linux/macOS
            tar -xzf fbcli-linux-amd64.tar.gz
            chmod +x fbcli
            
            # Windows
            # Extract fbcli.exe from zip file
            ```
          files: |
            ./artifacts/fbcli-linux-amd64/fbcli-linux-amd64.tar.gz
            ./artifacts/fbcli-linux-arm64/fbcli-linux-arm64.tar.gz
            ./artifacts/fbcli-windows-amd64/fbcli-windows-amd64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
